// Placeholder product photos (seeded, deterministic). Swap these for real
// product photography whenever you have it — just replace the `images` URLs.
const img = (seed) => `https://picsum.photos/seed/${seed}/1200/1500`;

export const PRODUCTS = [
  {
    id: "manto-preto-01",
    name: "Manto Onyx",
    category: "manto",
    type: "pronta",
    price: 189.9,
    sizes: ["P", "M", "G", "GG"],
    unavailable: ["P"],
    images: ["/produtos/camisa2.png"],
  },
  {
    id: "manto-verde-02",
    name: "Manto Vertex",
    category: "manto",
    type: "pronta",
    price: 199.9,
    sizes: ["P", "M", "G", "GG"],
    images: ["/produtos/camisa3.png"],
  },

  {
    id: "manto-custom-04",
    name: "Manto Titan Custom",
    category: "manto",
    type: "encomenda",
    price: 249.9,
    sizes: ["P", "M", "G", "GG", "XG"],
    images: ["/produtos/camisa3.png"],
  },
  {
    id: "chuteira-01",
    name: "Mercurial Vapor R9",
    category: "chuteira",
    type: "pronta",
    price: 349.9,
    sizes: ["37", "38", "39", "42", "43"],
    unavailable: ["38", "39"],
    images: [
      "/produtos/37/mercurial.jpeg",
      "/produtos/37/mercurial2.jpeg",
      "/produtos/37/mercurial1.jpeg",
    ],
  },
  {
    id: "chuteira-02",
    name: "Phantom GX II Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["37", "38", "39"],
    unavailable: ["38", "39"],
    images: [
      "/produtos/37/phantom1.jpeg",
      "/produtos/37/phantom.jpeg",
    ],
  },
  {
    id: "chuteira-custom-03",
    name: "Nike Air Zoom Vapor 16 Elite",
    category: "chuteira",
    price: 399.9,
    sizes: ["37", "38", "39", "43"],
    unavailable: ["39"],
    images: ["/produtos/37/airzoom.jpeg"],
  },
  {
    id: "chuteira-04",
    name: "Nike Phantom 6 Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["37", "38", "39", "42", "43"],
    unavailable: ["38"],
    images: [
      "/produtos/37/6elite.jpeg",
       "/produtos/37/6elite1.jpeg",
    ],
  },
   {
    id: "chuteira-05",
    name: "Nike Phantom GX 2 Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["37", "38", "39"],
    unavailable: ["38", "39"],
    images: [
      "/produtos/37/gx.jpeg",
    ],
   },
    {
    id: "chuteira-06",
    name: "Nike Air Zoom Vapor 16 Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["37", "38", "39", "40", "42", "43"],
    unavailable: ["39"],
    images: [
      "/produtos/37/vapor16.jpeg",
      "/produtos/37/VAPOR161.jpeg",
    ],
    },
    {
    id: "chuteira-07",
    name: "Nike Phantom 6 Black Mamba",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["37", "38", "39", "40"],
    unavailable: ["39"],
    images: [
      "/produtos/37/black.jpeg",
      "/produtos/37/black1.jpeg",
      "/produtos/37/black2.jpeg",
    ],
    },
    {
    id: "chuteira-08",
    name: "Nike Phantom GX II Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["37", "38", "39"],
    unavailable: ["39"],
    images: [
      "/produtos/37/gxii.jpeg",
      "/produtos/37/gxii1.jpeg",
      "/produtos/37/gxii2.jpeg",
    ],
    },
    {
    id: "chuteira-09",
    name: "Nike Phantom 6 Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["37", "38", "39", "41", "42", "43"],
    images: [
      "/produtos/37/phantom6.jpeg",
    ],
    },
    {
    id: "chuteira-10",
    name: "Adidas F50 LL ",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["37", "43,5"],
    images: [
      "/produtos/37/f50.jpeg",
      "/produtos/37/f501.jpeg",
    ],
    },
    {
    id: "chuteira-11",
    name: "Nike Phantom GX III Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["38", "39", "40", "43"],
    images: [
      "/produtos/38/GX1.jpeg",
      "/produtos/38/GXIII.jpeg",
    ],
    },
     {
    id: "chuteira-12",
    name: "Nike Air Zoom Vapor 16 Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["38", "39"],
    unavailable: ["39"],
    images: [
      "/produtos/38/16elite.jpeg",
      "/produtos/38/16elite1.jpeg",
    ],
    },
     {
    id: "chuteira-13",
    name: "Nike Phantom GX 2 Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["38", "39", "40"],
    unavailable: ["39"],
    images: [
      "/produtos/38/phantomgx.jpeg",

    ],
    },
     {
    id: "chuteira-14",
    name: "Nike Predador Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["38", "39", "42", "43"],
    unavailable: ["39"],
    images: [
      "/produtos/38/predador.jpeg",
        "/produtos/38/predador1.jpeg",

    ],
    },
     {
    id: "chuteira-15",
    name: "Nike Vapor 16 Elite ",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["38", "39"],
    unavailable: ["39"],
    images: [
      "/produtos/38/vapor161.jpeg",
        "/produtos/38/vapor16.jpeg",

    ],
    },
     {
    id: "chuteira-16",
    name: "Nike Phantom GX II Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["38", "39", "42", "43"],
    unavailable: ["39"],
    images: [
      "/produtos/38/elitefg.jpeg",

    ],
    },
     {
    id: "chuteira-17",
    name: "Adidas F50 Elite LL",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["38", "39"],
    unavailable: ["39"],
    images: [
      "/produtos/38/image1.png",
      "/produtos/38/image.png",

    ],
    },
    {
    id: "chuteira-18",
    name: "NIKE PHANTOM GX 2 ELITE",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["38", "39", "40"],
    unavailable: ["39"],
    images: [
      "/produtos/38/gx2.jpeg",
      "/produtos/38/gx21.jpeg",

    ],
    },
    {
    id: "chuteira-19",
    name: "Adidas Predator Elite 25 Laceless",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["38", "39"],
    unavailable: ["39"],
    images: [
      "/produtos/38/25elite1.jpeg",
      "/produtos/38/elite25.jpeg",

    ],
    },
     {
    id: "chuteira-20",
    name: "NIKE PHANTOM 6 ELITE LOW FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["39"],
    images: [
      "/produtos/39/ELITELOW.jpeg",

    ],
    },
     {
    id: "chuteira-21",
    name: "NIKE PHANTOM GX 2 ELITE FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["39"],
    images: [
      "/produtos/39/gx2.jpeg",
      "/produtos/39/gx21.jpeg",
    ],
    },
    {
    id: "chuteira-22",
    name: "NIKE PHANTOM GX ELITE ",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["39"],
    images: [
      "/produtos/39/gxelite1.jpeg",
      "/produtos/39/gxelite.jpeg",
    ],
    },
    {
    id: "chuteira-23",
    name: "NIKE AIR ZOOM VAPOR 17 ELITE ",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["39", "40", "43"],
    images: [
      "/produtos/39/vapor17.jpeg",
    ],
    },
    {
    id: "chuteira-24",
    name: "NIKE PHANTOM 6 PRO ",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["39", "40", "41", "43"],
    images: [
      "/produtos/39/6pro1.jpeg",
      "/produtos/39/6pro.jpeg",
    ],
    },
    {
    id: "chuteira-25",
    name: "Nike Phantom 6 Elite Low",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "41"],
    images: [
      "/produtos/40/Nike Phantom 6 Elite Low.jpeg",
    ],
    },
    {
    id: "chuteira-26",
    name: "Nike Phantom GX Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "41", "43"],
    images: [
      "/produtos/40/Nike Phantom GX Elite.jpeg",
    ],
    },
     {
    id: "chuteira-27",
    name: "Nike Phantom 6 Elite Low FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "43 "],
    images: [
      "/produtos/40/Nike Phantom 6 Elite Low FG.jpg",
    ],
    },
    {
    id: "chuteira-28",
    name: "Nike Phantom GX Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40"],
    images: [
      "/produtos/40/Nike Phantom GX Elite FG.jpg",
      "/produtos/40/Nike Phantom GX Elite FG1.webp",
    ],
    },
    {
    id: "chuteira-29",
    name: "Nike Air Zoom Mercurial Vapor 16 Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "41","43"],
    images: [
      "/produtos/40/Nike Air Zoom Mercurial Vapor 16 Elite.jpeg",
      "/produtos/40/Nike Air Zoom Mercurial Vapor 16 Elite1.webp",
    ],
    },
    {
    id: "chuteira-30",
    name: "Nike Phantom 6 Elite Low FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "43"],
    images: [
      "/produtos/40/Nike Phantom 6 Elite Low FG1.jpg",
      "/produtos/40/Nike Phantom 6 Elite Low FG2.png",
    ],
    },
    {
    id: "chuteira-31",
    name: "Nike Phantom 6 Elite Low FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "43"],
    images: [
      "/produtos/40/Nike Phantom 6 Elite Low FG3.jpg",
      "/produtos/40/Nike Phantom 6 Elite Low FG4.jpg",
    ],
    },
     {
    id: "chuteira-32",
    name: "Nike Phantom GX Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "43"],
    images: [
      "/produtos/40/Nike Phantom GX Elite2.webp",
      "/produtos/40/Nike Phantom GX Elite3.webp",
    ],
    },
    {
    id: "chuteira-33",
    name: "Nike Phantom GX Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "43"],
    images: [
      "/produtos/40/Nike Phantom GX Elite4.jpg",
      "/produtos/40/Nike Phantom GX Elite5.jpg",
    ],
    },
  {
    id: "chuteira-34",
    name: "Nike Phantom GX 2 Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40"],
    images: [
      "/produtos/40/Nike Phantom GX 2 Elite FG.jpeg",
      "/produtos/40/Nike Phantom GX 2 Elite FG.png",
    ],
    },
    {
    id: "chuteira-35",
    name: "adidas F50 Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "42"],
    images: [
      "/produtos/40/adidas F50 Elite FG1.jpg",
      "/produtos/40/adidas F50 Elite FG.avif",
    ],
    },
     {
    id: "chuteira-36",
    name: "Nike Phantom GX II Elite FG United 001",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "42"],
    images: [
      "/produtos/40/Nike Phantom GX II Elite FG United 0012.webp",
      "/produtos/40/Nike Phantom GX II Elite FG United 0011.jfif",
       "/produtos/40/Nike Phantom GX II Elite FG United 001.webp",
    ],
    },
    {
    id: "chuteira-37",
    name: "Nike Zoom Mercurial Vapor 16 Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["40", "41"],
    images: [
      "/produtos/40/Nike Zoom Mercurial Vapor 16 Elite.jpeg",
      "/produtos/40/Nike Zoom Mercurial Vapor 16 Elite1.jfif",
    ],
    },
    {
    id: "chuteira-38",
    name: "Puma Ultra 5 Ultimate FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["41"],
    images: [
      "/produtos/41/Puma Ultra 5 Ultimate FG.jpeg",
      "/produtos/41/Puma Ultra 5 Ultimate FG1.jpeg",
    ],
    },
    {
    id: "chuteira-39",
    name: "Nike Air Zoom Mercurial Vapor 16 Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["41", "43"],
    images: [
      "/produtos/41/Nike Air Zoom Mercurial Vapor 16 Elite FG.jpg",
      "/produtos/41/Nike Air Zoom Mercurial Vapor 16 Elite FG1.webp",
    ],
    },
    {
    id: "chuteira-40",
    name: "Nike Phantom 6 Elite LE",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["41", "43 "],
    images: [
      "/produtos/41/Nike Phantom 6 Elite LE.jpg",
      "/produtos/41/Nike Phantom 6 Elite LE1.webp",
    ],
    },
    {
    id: "chuteira-41",
    name: "Nike Air Zoom Mercurial Superfly 10 Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["41"],
    images: [
      "/produtos/41/Nike Air Zoom Mercurial Superfly 10 Elite.jpg",
      "/produtos/41/Nike Air Zoom Mercurial Superfly 10 Elite.webp",
    ],
    },
    {
    id: "chuteira-42",
    name: "Adidas F50 Hyperfast Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["41"],
    images: [
      "/produtos/41/Adidas F50 Hyperfast Elite FG1.webp",
      "/produtos/41/Adidas F50 Hyperfast Elite FG.avif",
    ],
    },
    {
    id: "chuteira-43",
    name: "Nike Phantom 6 Elite Low ",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["41"],
    images: [
      "/produtos/41/Nike Phantom 6 Elite Low 1.webp",
      "/produtos/41/Nike Phantom 6 Elite Low .jpeg",
    ],
    },
    {
    id: "chuteira-44",
    name: "Nike Air Zoom Mercurial Vapor 16 Elite ",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["41", "42"],
    images: [
      "/produtos/41/Nike Air Zoom Mercurial Vapor 16 Elite2.webp",
      "/produtos/41/Nike Air Zoom Mercurial Vapor 16 Elite3.webp",
    ],
    },
    {
    id: "chuteira-45",
    name: "Nike Air Zoom Mercurial Vapor 16 Elite FG ",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["41"],
    images: [
      "/produtos/41/Nike Air Zoom Mercurial Vapor 16 Elite FG.jpeg",
      
    ],
    },
    {
    id: "chuteira-46",
    name: "Nike Mercurial Superfly 10 Elite",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["42"],
    images: [
        "/produtos/42/42-011.webp",
         "/produtos/42/42-0112.webp",
    ],
},
{
    id: "chuteira-47",
    name: "Nike Phantom GX 2 Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["42"],
    images: [
        "/produtos/42/42-031.webp",
        "/produtos/42/42-032.webp",
    ],
},
{
    id: "chuteira-48",
    name: "Adidas F50 Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["42"],
    images: [
        "/produtos/42/42-091.jpg",
         "/produtos/42/42-092.webp",
    ],
},
{
    id: "chuteira-49",
    name: "Nike Mercurial Vapor 16 Elite FG ",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["42"],
    images: [
        "/produtos/42/42-172.webp",
        "/produtos/42/42-171.jpg",
    ],
},
{
    id: "chuteira-50",
    name: "Nike Mercurial Superfly 10 Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["42"],
    images: [
        "/produtos/42/42-191.jpg",
        "/produtos/42/42-192.jfif",
    ],
},
{
    id: "chuteira-51",
    name: "Nike Air Zoom Mercurial Vapor 16 Elite FG",
    category: "chuteira",
    type: "pronta",
    price: 329.9,
    sizes: ["42"],
    images: [
        "/produtos/42/42-29.webp",
        "/produtos/42/42-29.webp",
    ],
},
];